vota_prato/config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :qualificacaos
  resources :clientes
  resources :restaurantes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

vota_prato/app/models/qualificacao.rb
class Qualificacao < ApplicationRecord
  validates_presence_of :nota, message: " - deve ser preenchido"
  validates_presence_of :valor_gasto, message: " - deve ser preenchido"
  validates_numericality_of :nota, greater_than_or_equal_to: 0,
                            less_than_or_equal_to: 10,
                            message: " - deve ser um número entre 0 e 10"
  validates_numericality_of :valor_gasto, greater_than: 0,
                            message: " - deve ser um número maior que 0"
  belongs_to :cliente
  belongs_to :restaurante
  has_many :comentarios, as: :comentavel
  validates_presence_of :cliente_id, :restaurante_id
  validates_associated :cliente, :restaurante

end

vota_prato/app/controllers/qualificacaos_controller.rb
class QualificacaosController < ApplicationController
  before_action :set_qualificacao, only: [:show, :edit, :update, :destroy]

  # GET /qualificacaos
  # GET /qualificacaos.json
  def index
    @qualificacaos = Qualificacao.all
  end

  # GET /qualificacaos/1
  # GET /qualificacaos/1.json
  def show
  end

  # GET /qualificacaos/new
  def new
    preparar_form
    @qualificacao = Qualificacao.new

    if params[:cliente]
        @qualificacao.cliente = Cliente.find(params[:cliente])
     end
    if params[:restaurante]
      @qualificacao.restaurante = Restaurante.find(params[:restaurante])
    end
  end

  # GET /qualificacaos/1/edit
  def edit
    preparar_form
  end

  # POST /qualificacaos
  # POST /qualificacaos.json
  def create
    @qualificacao = Qualificacao.new(qualificacao_params)

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully created.' }
        format.json { render :show, status: :created, location: @qualificacao }
      else
        preparar_form
        format.html { render :new }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualificacaos/1
  # PATCH/PUT /qualificacaos/1.json
  def update
    @qualificacao = Qualificacao.find(params[:id])
    respond_to do |format|
      if @qualificacao.update(qualificacao_params)
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @qualificacao }
      else
        format.html { render :edit }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacaos/1
  # DELETE /qualificacaos/1.json
  def destroy
    @qualificacao.destroy
    respond_to do |format|
      format.html { redirect_to qualificacaos_url, notice: 'Qualificacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualificacao
      @qualificacao = Qualificacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualificacao_params
      params.require(:qualificacao).permit(:cliente_id, :restaurante_id, :nota, :valor_gasto)
    end
  private
  def preparar_form
    @clientes = Cliente.order :nome
    @restaurantes = Restaurante.order :nome
  end
end

vota_prato/app/helpers/qualificacaos_helper.rb
module QualificacaosHelper
end

vota_prato/app/views/qualificacaos/_form.html.erb
<%= form_for(qualificacao) do |f| %>
  <% if qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% qualificacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if @qualificacao.cliente %>
        <%= f.hidden_field 'cliente_id' %>
    <% else %>
        <p><%= f.label :cliente_id %> <br />
          <%= f.collection_select(:cliente_id, @clientes,
                                  :id, :nome, :prompt => true) %> </p>
    <% end %>

    <% if @qualificacao.restaurante %>
        <%= f.hidden_field 'restaurante_id' %>
    <% else %>
        <p><%= f.label :restaurante_id %> <br />
          <%= f.collection_select(:restaurante_id, @restaurantes,
                                  :id, :nome, :prompt => true) %> </p>
    <% end %>

  <div class="field">
    <%= f.label :nota %>
    <%= f.text_field :nota %>
  </div>

  <div class="field">
    <%= f.label :valor_gasto %>
    <%= f.text_field :valor_gasto %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vota_prato/app/views/qualificacaos/edit.html.erb
<h1>Editing Qualificacao</h1>

<%= render 'form', qualificacao: @qualificacao %>

<%= link_to 'Show', @qualificacao %> |
<%= link_to 'Back', qualificacaos_path %>

vota_prato/app/views/qualificacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qualificacaos</h1>

<table border="1">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Restaurante</th>
      <th>Nota</th>
      <th>Valor gasto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualificacaos.each do |qualificacao| %>
      <tr>
        <td><%= qualificacao.cliente_id %></td>
        <td><%= qualificacao.restaurante_id %></td>
        <td><%= qualificacao.nota %></td>
        <td><%= valor_formatado(qualificacao.valor_gasto) %></td>
        <td><%= link_to 'Show', qualificacao %></td>
        <td><%= link_to 'Edit', edit_qualificacao_path(qualificacao) %></td>
        <td><%= link_to 'Destroy', qualificacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualificacao', new_qualificacao_path %>

vota_prato/app/views/qualificacaos/new.html.erb
<h1>New Qualificacao</h1>

<%= render 'form', qualificacao: @qualificacao %>

<%= link_to 'Back', qualificacaos_path %>

vota_prato/app/views/qualificacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @qualificacao.cliente_id %>
</p>

<p>
  <strong>Restaurante:</strong>
  <%= @qualificacao.restaurante_id %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @qualificacao.nota %>
</p>

<p>
  <strong>Valor gasto:</strong>
  <%= valor_formatado(@qualificacao.valor_gasto) %>
</p>
<%=novo_comentario @restaurante%>
<%=novo_comentario @qualificacao%>

<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacaos_path %>